-- MySQL Script generated by MySQL Workbench
-- Thu May 11 13:17:21 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bapp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bapp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jasonkel_bapp` DEFAULT CHARACTER SET utf8 ;
USE `jasonkel_bapp` ;

-- -----------------------------------------------------
-- Table `bapp`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jasonkel_bapp`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP(6) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bapp`.`contact_persons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jasonkel_bapp`.`contact_persons` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `phone` INT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP(6) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bapp`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jasonkel_bapp`.`groups` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bapp`.`members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jasonkel_bapp`.`members` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `contact_person_id` INT UNSIGNED NOT NULL,
  `group_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `members_contact_persons_idx` (`contact_person_id` ASC),
  INDEX `members_groups_idx` (`group_id` ASC),
  CONSTRAINT `members_contact_persons`
    FOREIGN KEY (`contact_person_id`)
    REFERENCES `jasonkel_bapp`.`contact_persons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `members_groups`
    FOREIGN KEY (`group_id`)
    REFERENCES `jasonkel_bapp`.`groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
